name: CI - Run Tests

on:
  push:
    branches:
      - main
      - dev
      - update2
  pull_request:
    branches:
      - main
      - dev
      - update2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Set working directory to src/backend where package-lock.json exists
      - name: Set working directory
        run: cd src/backend

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        working-directory: src/backend
        run: npm ci

      # Run tests
      - name: Run tests
        working-directory: src/backend
        run: npm test
